# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AhmedSoloApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AhmedSoloApp
 pod 'Firebase/Analytics'	
pod 'Firebase/Auth'	
pod 'Firebase/Firestore'	
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'SkyFloatingLabelTextField'
pod 'Firebase/Database'

pod 'youtube-ios-player-helper'
pod 'SVProgressHUD'
pod 'SCLAlertView'
pod 'SideMenu'



end
